require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiariesController do
  before(:each) do
    @user = create_default_twitter_user
    session[:user_id] = @user.id

    @diary = FactoryGirl.build(:diary)
    @diary.users << @user
    @diary.save
  end

  # This should return the minimal set of attributes required to create a valid
  # Diary. As you add validations to Diary, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      title:   "another diary",
      deliver: true,
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiariesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all diaries as @diaries" do
      get :index #, {}, valid_session
      assigns(:diaries).should eq([@diary])
    end
  end

  describe "GET show" do
    it "assigns the requested diary as @diary" do
      get :show, {:id => @diary.to_param}
      assigns(:diary).should eq(@diary)
    end
  end

  describe "GET new" do
    it "assigns a new diary as @diary" do
      get :new
      assigns(:diary).should be_a_new(Diary)
    end
  end

  describe "GET edit" do
    it "assigns the requested diary as @diary" do
      get :edit, {:id => @diary.to_param}
      assigns(:diary).should eq(@diary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diary" do
        expect {
          post :create, {:diary => valid_attributes}
        }.to change(Diary, :count).by(1)
      end

      it "assigns a newly created diary as @diary" do
        post :create, {:diary => valid_attributes}
        assigns(:diary).should be_a(Diary)
        assigns(:diary).should be_persisted
      end

      it "redirects to the created diary" do
        post :create, {:diary => valid_attributes}
        response.should redirect_to(diaries_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diary as @diary" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diary.any_instance.stub(:save).and_return(false)
        post :create, {:diary => {}}
        assigns(:diary).should be_a_new(Diary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diary.any_instance.stub(:save).and_return(false)
        post :create, {:diary => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diary" do
        # Assuming there are no other diaries in the database, this
        # specifies that the Diary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Diary.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => @diary.to_param, :diary => {'these' => 'params'}}
      end

      it "assigns the requested diary as @diary" do
        put :update, {:id => @diary.to_param, :diary => valid_attributes}
        assigns(:diary).should eq(@diary)
      end

      it "redirects to the diary" do
        put :update, {:id => @diary.to_param, :diary => valid_attributes}
        response.should redirect_to(diaries_url)
      end
    end

    describe "with invalid params" do
      it "assigns the diary as @diary" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diary.any_instance.stub(:save).and_return(false)
        put :update, {:id => @diary.to_param, :diary => {}}
        assigns(:diary).should eq(@diary)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diary.any_instance.stub(:save).and_return(false)
        put :update, {:id => @diary.to_param, :diary => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diary" do
      expect {
        delete :destroy, {:id => @diary.to_param}
      }.to change(Diary, :count).by(-1)
    end

    it "redirects to the diaries list" do
      delete :destroy, {:id => @diary.to_param}
      response.should redirect_to(diaries_url)
    end
  end

  describe "DELETE withdraw" do
    it "withdraw from the diary" do
      expect {
        delete :withdraw, {:id => @diary.to_param}
      }.to change(Member, :count).by(-1)
    end

    it "redirects to the diaries list" do
      delete :withdraw, {:id => @diary.to_param}
      response.should redirect_to(diaries_url)
    end
  end

end
